name: Auto merge
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --shallow-since "$(date -d "$(date +'%Y-%m-01') 1 month ago" +'%Y/%m/%d')"
          echo ''
          git log --graph --pretty=format:"%h %ad %s"
          echo ''
          git branch -a
          export CURRENT_BRANCH=$(git name-rev --name-only HEAD)
          echo ''
          git switch $CURRENT_BRANCH
          echo ''
          git switch main
          echo ''
          git log --graph --pretty=format:"%h %ad %s"
        #  git merge --no-ff $CURRENT_BRANCH
      - run: git log --graph --pretty=format:"%h %ad %s"