name: Auto merge
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch
        run: |
          git fetch --shallow-since "$(date -d "$(date +'%Y-%m-01') 1 month ago" +'%Y/%m/%d')"
          git switch main
          git merge --no-ff $(git name-rev --name-only HEAD)
