name: Auto merge
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch
        run: |
          git fetch --shallow-since "$(date -d "$(date +'%Y-%m-01') 1 month ago" +'%Y/%m/%d')"
          git switch main
      - name: print
        run: |
          git branch
          git log
          echo $BRANCH_NAME
        env:
          BRANCH_NAME: ${{ github.head_ref }}
