name: Auto merge
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ github.event.pull_request.head.sha }}'
      - uses: actions/checkout@v2
        with:
          ref: patch-1
      - name: print
        run: |
          pwd
          git branch
          git log
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: print
        run: |
          pwd
          git branch
          git log